version: "3.3"

services:
  course-recommender:
    hostname: ${RECOMMENDER_HOSTNAME}
    container_name: ${RECOMMENDER_HOSTNAME}
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    environment:
